{
 "title": "Crypto Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "coin_type", "query": { "query": "label_values(coin_type)" } },
   {
    "name": "endpoint",
    "query": {
     "query": "label_values(crypto_price_successful_requests_total,exported_endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "crypto_price_successful_requests_total{coin_type=~\"$coin_type\", exported_endpoint=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Site returned no price",
   "type": "timeseries",
   "description": "This might happen if the user tries to get an invalid coin",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "crypto_price_not_found_error_total{exported_endpoint=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Api errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "endpoint_api_error_total{exported_endpoint=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}